server:
  port: 9000
spring:
  application:
    name: dm-user-provider
  zipkin:
    base-url: http://localhost:7700
  sleuth:
    sampler:
      percentage: 1.0
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7777/eureka