server:
  port: 8002
spring:
  application:
    name: dm-user-consumer-second
eureka:
  client:
    service-url:
      defaultZone: http://root:123456@localhost:7777/eureka
feign:
  hystrix:
    enabled: true